services:
  api:
    build: .
    container_name: blacksilver_api
    ports:
      - "${APP_PORT:-9095}:9095" # si no hay APP_PORT en el .env, usará el 9095 por defecto
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"